language: python
services:
  - docker
python:
  - "3.6"
install:
  - make deps
script:
  - make lint
  - make test
  - make docker_build
after_success:
  -make docker_push
deploy:
provider: heroku
app: secure-plains-18224
#api_key: ${HEROKU_API_KEY}
